services:
  web-mvc:
    container_name: web-mvc
    image: ${DOCKER_REGISTRY-}web-mvc
    build:
      context: .
      dockerfile: src/mvc/Web.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 17429:8080
    depends_on:
      - account-microservice-api
      - redis
    env_file:
      - "./general.env"

  api-gateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}api-gateway
    build:
      context: .
      dockerfile: src/gateway/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 22521:8080

  account-microservice-api:
    container_name: account-microservice-api
    image: ${DOCKER_REGISTRY-}accountmicroservice-api
    build:
      context: .
      dockerfile: src/microservices/account/AccountMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 32167:8080
    env_file:
      - "./src/microservices/account/AccountMicroservice.Api/app.env"
      - "./general.env"
    depends_on:
      - postgres-account
      - api-gateway

  category-microservice-api:
    container_name: category-microservice-api
    image: ${DOCKER_REGISTRY-}categorymicroservice-api
    build:
      context: src/microservices/category/CategoryMicroservice.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 32166:8080
    env_file:
      - "./general.env"
    depends_on:
      - postgres-category
      - api-gateway

  postgres-category:
    container_name: postgres-category
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ReviewsPlatformCategoryMicroservice
    volumes:
      - postgres-category-data:/var/lib/postgresql

  postgres-account:
    container_name: postgres-account
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ReviewsPlatformAccountMicroservice
    volumes:
      - postgres-account-data:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres-account-data: {}
  postgres-category-data: {}
  redis_data: {}