services:
  web-mvc:
    container_name: web-mvc
    image: ${DOCKER_REGISTRY-}web-mvc
    build:
      context: .
      dockerfile: src/mvc/Web.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 17429:8080
    depends_on:
      - account-microservice-api

  api-gateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}api-gateway
    build:
      context: .
      dockerfile: src/gateway/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 22521:8080

  account-microservice-api:
    container_name: account-microservice-api
    image: ${DOCKER_REGISTRY-}accountmicroservice-api
    build:
      context: .
      dockerfile: src/microservices/account/AccountMicroservice.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 32167:8080
    depends_on:
      - postgres-account
      - api-gateway

  postgres-account:
    container_name: postgres-account
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ReviewsPlatformAccountMicroservice
    volumes:
      - postgres-account-data:/var/lib/postgresql

volumes:
  postgres-account-data: {}  